class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start2'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzipmirror2'
        self.TarMirrorCommand = 'tarmirror2'
        self.ZipMirrorCommand = 'zipmirror2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cancelall2'
        self.ListCommand = 'list2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats2'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone2'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.ZipWatchCommand = 'zipwatch2'
        self.QbMirrorCommand = 'qbmirror2'
        self.QbUnzipMirrorCommand = 'qbunzipmirror2'
        self.QbTarMirrorCommand = 'qbtarmirror2'
        self.QbZipMirrorCommand = 'qbzipmirror2'
        self.DeleteCommand = 'del2'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp2'

BotCommands = _BotCommands()
